language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t Alexius2308/docker-react -f Dockerfile.dev .

script:
  -  docker run -e CI=true Alexius2308/docker-react -react npm run test