language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t alexius2308/docker-react -f Dockerfile.dev .

script:
  -  docker run -e CI=true alexius2308/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-499763893946"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
